//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEginfoRH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public class EGINFORHContext : DbContext
    {
        public EGINFORHContext() : base("name=ModeloDados")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Candidato>()
                            
                .HasMany<Especialidade>(s => s.Especialidades)
                .WithMany(c => c.Candidatos)
                .Map(cs =>
                {
                    cs.MapLeftKey("idCandidato");
                    cs.MapRightKey("idEspecialidade");
                    cs.ToTable("tb_Detalhe_Candidato");
                });
        }

        public virtual DbSet<Candidato> Candidatos { get; set; }
        public virtual DbSet<Especialidade> Especialidades { get; set; }
    }
}